import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt 

#Read cleaned pharmacy Sales data 
df = pd.read_excel ("pharmacy_Cleaned_sale.xlsx")

#Total Revenue Generated
print("\nTotal Revenue Generated ")
print(df["Total_Sales"]. sum())

#Average Revenue 
print("\nAVERAGE REVENUE")
print(df["Total_Sales"].mean())

#Highest Sales 
print("\nHighest Sales")
print(df["Total_Sales"].max())

#Lowest Sales 
print("\nLowest Sales")
print(df["Total_Sales"].min())


# Products Analysis
print("\nHighest Revenue by Product")
top_product_sales = (
df.groupby("Product_Name")["Total_Sales"]. sum()
.sort_values(ascending=False)
)

print(top_product_sales.head(10))

print("\nLowest Revenue by Product")
top_product_sales = (
df.groupby("Product_Name")["Total_Sales"]. sum()
.sort_values(ascending=True)
.head(10))
print(top_product_sales)

#Products with Highest Quantity Sold
print("\nHighest Quantity Sold")
high_product_quantity =(
df.groupby("Product_Name")["Quantity_Sold"].sum()
.sort_values (ascending =False)
.head(5))

print(high_product_quantity)


#Category Analysis 
print("\nCategory with the highest Revenue")

top_category_sales =(
df.groupby("Category")["Total_Sales"]. sum()
.sort_values(ascending=False)
.head(5))
print(top_category_sales)

print("\nCategory with the Lowest Revenue ")
lowest_category_sales =(
df.groupby("Category")["Total_Sales"]. sum()
.sort_values(ascending=True))

print(lowest_category_sales.head(5))

print("\nCategory with Highest Quantity Sold ")
High_category_quantity =(
df.groupby("Category")["Quantity_Sold"]. sum()
.sort_values(ascending=False))

print(High_category_quantity)

print ("\nRevenue Generated by Category (%)")
Category_percentage = (top_category_sales/top_category_sales.sum()) * 100

print(Category_percentage.round(2))

#Suppliers Analysis 
print("\nSuppliers with Highest Revenue")
High_Sup_Rev = (
df.groupby("Suppliers")["Total_Sales"]. sum()
.sort_values(ascending=False)
.head())

print(High_Sup_Rev)

print("\nSuppliers with Lowest Revenue")
Low_Sup_Rev =(
df.groupby("Suppliers")["Total_Sales"]. sum()
.sort_values(ascending=True)
.head())

print(Low_Sup_Rev)

print("Products Supplied by each Supplier")

no_of_product_sup = (
df.groupby("Suppliers")["Product_Name"].count())

print(no_of_product_sup)

#Inventory Analysis 
print("\nPRODUCTS WITH HIGHEST STOCKS")

highest_stock_product = (
df.groupby("Product_Name")["Stock_In_Hand"]. sum()
.sort_values(ascending=False)
.head())

print(highest_stock_product)

print("\nPRODUCTS WITH LOWEST STOCKS ")

lowest_stock_product =(
df.groupby("Product_Name")["Stock_In_Hand"]. sum()
.sort_values(ascending=True)
.head(5))

print(lowest_stock_product)

# Product Needing Restock
#Assuming you want to restock Products with less than 50 units 
print("\nProducts Needing Restock")

restock =(
df[df["Stock_In_Hand"] < 50])

print(restock[["Product_Name",  "Category",  "Stock_In_Hand",  "Suppliers"]])

#Average Stocks Level
print("\nAverage Stocks Level")
average_stock = df["Stock_In_Hand"].mean()

print(average_stock)

#Already Expired Products
#Convert Expire_Date columns to datetime format 
df["Expire_Date"] = pd.to_datetime(df["Expire_Date"])

print("\nAlready Expired Products")
expired =(df[df["Expire_Date"] < pd.Timestamp.today()])

print(expired[["Product_Name", "Expire_Date", "Stock_In_Hand"]])

#Products Expiring within the next 30days
print("\nProducts Expiring within 30 Days")

today = pd.Timestamp.today()

next_30_days = today + pd.Timedelta(days=30)
expiring_soon = (
df[
(df["Expire_Date"] >= today) & 
(df["Expire_Date"] <= next_30_days)
]
)

print(expiring_soon[["Product_Name",  "Expire_Date",  "Stock_In_Hand"]])

#Days Remaining Before Expiry
df["Days_Remaining"] = (df["Expire_Date"] - pd.Timestamp.today()).dt.days

print(df[["Product_Name",  "Stock_In_Hand", "Expire_Date", "Days_Remaining"]])

# Quantity at Risk of Expiring 

print("\nQuantity At Risk Of Expiring")
quantity_at_risk = (
expiring_soon["Stock_In_Hand"]. sum())

print(quantity_at_risk)

#Sales Trend Analysis or (Time Series Analysis )

#Daily Sales Trend 
print("\nDaily Sales")
daily_sales =(
df.groupby("Date")["Total_Sales"]. sum()
.sort_index())

print(daily_sales)

# Lowest Sales Day
print("\nLowest Sales Day")

daily_sales = (
    df.groupby("Date")["Total_Sales"]
    .sum()
)

lowest_sales_date = daily_sales.idxmin()
lowest_sales_amount = daily_sales.min()

print("Date:", lowest_sales_date)
print("Sales:", lowest_sales_amount)

#Highest Sales Day
print("\nHighest Sales Day")

daily_sales = (
df.groupby("Date")["Total_Sales"]. sum()
)

highest_sales_date = daily_sales.idxmax()
highest_sales_amount = daily_sales.max()

print("Date:", highest_sales_date)
print("Sales:", highest_sales_amount)

#Best Selling Products By Category 
print("\nBest Selling Products By Category")
best_category_product = (
df.groupby(["Category",  "Product_Name"])["Quantity_Sold"]. sum()
.sort_values (ascending =False)
)

print(best_category_product)

#Revenue Generated Per Unit Sold
print("\nRevenue Generated Per Unit Sold")

total_revenue = df["Total_Sales"].sum()
total_quantity = df["Quantity_Sold"].sum()

revenue_per_unit = total_revenue / total_quantity 

print(round(revenue_per_unit, 2))

#Fast Moving Products 
print("\nTop 10 Fast Moving Products")

fast_moving = (
df.groupby("Product_Name")["Quantity_Sold"]. sum()
.sort_values(ascending=False))

print(fast_moving.head(10))

print("\nTop 10 Slow Moving Products")

slow_moving = (
df.groupby("Product_Name")["Quantity_Sold"]. sum()
.sort_values(ascending=True))

print(slow_moving.head(10))

####DASHBOARD CHARTS ANALYSIS 

#Chart 1: Revenue by Category 

revenue_category = (
df.groupby("Category")["Total_Sales"]. sum()
.sort_values(ascending=False))


plt.figure (figsize =(8, 5))
revenue_category.plot(kind="bar")

# Add revenue values on top of each bar
for i, value in enumerate(revenue_category.values):
    plt.text(
        i,
        value + 1000,        # Slightly above the bar
        f"{int(value):,}",   # Display with commas (e.g. 200,100)
        ha="center",
        fontsize=12
    )

plt.title ("Revenue by Category")
plt.xlabel ("Category")
plt.ylabel ("Total Revenue")

plt.tight_layout ()
plt.savefig ("pharmacy Revenue by Product.png")

plt.close()

#Chart 2: Top 10 Products By Revenue 
revenue_product = (
df.groupby("Product_Name")["Total_Sales"]. sum()
.sort_values(ascending=False)
.head(10))

plt.figure (figsize =(8, 5))
revenue_product.plot(kind ="barh")
plt.gca().invert_yaxis()

for i, value in enumerate(revenue_product.values):
	plt.text(value + 1000, i, f"{int(value): ,}", va="center",  fontsize=12)
	
plt.title ("Top 10 Products By Revenue")
plt.xlabel ("Total Revenue")
plt.ylabel ("Product Name")

plt.tight_layout ()
plt.savefig ("pharmacy Top 10 Revenue by Product.png")
plt.close()

#Chart 3:  Quantity Sold by Products 
quantity_product = (
df.groupby("Product_Name")["Quantity_Sold"]. sum()
.sort_values(ascending=False))

plt.figure (figsize =(8, 5))
quantity_product.plot(kind="bar")

for i, value in enumerate (quantity_product.values):
	plt.text(i, value + 1, f"{int(value):,}", ha="center",  fontsize=12)
	
plt.title ("Quantity Sold by Products")
plt.xlabel ("Product Name")
plt.ylabel ("Quantity Sold")

plt.tight_layout ()

plt.savefig ("pharmacy Quantity Sold by Product.png")
plt.close()

#Chart 4: Supplier Revenue Contribution 
suppler_revenue = (
df.groupby("Suppliers")["Total_Sales"]. sum()
.sort_values(ascending=False))

plt.figure (figsize =(10, 5))
suppler_revenue.plot(kind="pie", autopct="%1.1f%%")

plt.title ("Suppliers Revenue Contribution")
plt.tight_layout ()
plt.savefig ("pharmacy Suppliers Revenue Contribution.png")
plt.close()

#Chart 5: Daily Sales Trend 
daily_sales = (
df.groupby("Date")["Total_Sales"]. sum())

plt.figure (figsize =(10, 5))
daily_sales.plot(kind="line", marker="o")

for i, value in enumerate(daily_sales.values):
	plt.text (i, value + 1000, f"{int(value):,}", ha="center", fontsize=8)
	
	
plt.title ("Daily Sales Trend")
plt.xlabel ("Date")
plt.ylabel ("Daily Revenue")
plt.tight_layout ()

plt.savefig ("pharmacy Daily Sales Trend.png")
plt.close()

#Chart 6: Stocks Remaining by products
stock_product=(
df.groupby("Product_Name")["Stock_In_Hand"]. sum()
.sort_values(ascending=False)
.head(10))

plt.figure (figsize =(8, 5))

stock_product.plot(kind ="barh")
plt.gca().invert_yaxis()

for i, value in enumerate (stock_product.values):
	plt.text((value + 1), i, f"{int(value):,}", va="center", fontsize =10)
	
plt.title ("Stocks Remaining by products")
plt.xlabel ("Stock_In_Hand")
plt.ylabel ("Product Name")

plt.tight_layout ()
plt.savefig ("pharmacy Stocks Remaining by products.png")
plt.close()

#Chart 7: Revenue contribution by Category(%)

top_category_sales = (
df.groupby("Category")["Total_Sales"]. sum()
.sort_values(ascending=False)
.head(10))
Category_percentage = (top_category_sales/top_category_sales.sum()) * 100

plt.figure (figsize =(10, 5))

Category_percentage.plot(kind ="pie", autopct="%1.1f%%")

plt.title ("Revenue Contribution by Category (%)")

plt.tight_layout ()

plt.savefig("pharmacy Revenue Contribution by Category(%).png")
plt.close()

#Chart 8: Fast Moving Products 

fast_moving = (
df.groupby("Product_Name")["Quantity_Sold"]. sum()
.sort_values(ascending=False))

plt.figure (figsize =(10, 5))
fast_moving.plot(kind ="barh")
plt.gca().invert_yaxis()

for i, value in enumerate (fast_moving.values):
	plt.text (value + 1, i, f"{int(value):,}", va="center",  fontsize=10)
	
plt.title ("Fast Moving Products")
plt.xlabel ("Quantity Sold")
plt.ylabel ("Product Name")

plt.tight_layout ()
plt.savefig ("pharmacy Fast Moving Products.png")
plt.close()





